name = "QEMU aarch64"

[spec]
arch = "aarch64"
storage = "virt"

[use]
u-boot = "mainline"
linux = "mainline"

[u-boot]
config = "qemu_arm64_defconfig"

[linux]
config = "defconfig"

[disk]
format = "qcow2"
